### ISSUE TITLE
Detailed instructions for Agent Payment Flow

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Handbook#10]
AGENT PAYMENT FLOW

This same flow applies both to internal work and client work:

1. Enter claim into [budget spreadsheet](https://sheet.zoho.com/sheet/open/a4p9k334be0a1097242a3b83d72f227695a48/sheets/CENNZnet/ranges/F5)

2. Once everyone in your claim has filled in and agreed to distribution, move details into the [compensation request form](https://airtable.com/shrSsOJJUoM6N6IKL)

3. Form will redirect to alchemy proposal. Make sure to enter your ETH address, payment, token, and Reputation amount in the proposal form.

**Comment by benefacto** [comment]
I'd like to understand this process fully so I can make effective documentation for it.

**Comment by benefacto** [comment]
Thoughts so far:

- Current process:
  - The client actual payments are the ones typically divided among agents via allocations
  - Agents can split out the payments how they want into further blocks, though
  - Allocation is corresponds more to how much of the results did you deliver, not corresponding to effort
- Possible changes
  - Goal: incentivize participation and contribution
    - Participation by agents is important as it increases dOrg’s capacity and reduces project risk by balancing the workload among multiple agents 
    - Contribution by agents is important as the quality & timeliness of projects reflects directly on dOrg’s reputation and its ability to obtain more work
  - Start by figuring this out on a kickoff call for a given project, the project manager should handle scheduling most of this and make sure it happens:
    - Start with an expected allocation for each agent: this will be used for budget, resources, and guidelines
    - Determine distribution ratio/algorithm: hours vs. focused contribution vs. hybrid (maybe based on voting to add weighted modifiers to each agents’ allocation)
    - Schedule distribution points: meetings when periodic payments to agents will be calculated and made (possibly when distribution ratio/algorithm will be re-determined based on project work remaining)
  - Participants keep a work log with hours, and what they did, self organizing
  - At distribution points, agents list hours, conversation on degree/rank/modifier of contribution: distribution point becomes block (possibly when re-determined distribution ratio/algorithm will be based on project work remaining)

**Comment by benefacto** [comment]
Add the following pages to a new section called WORKFLOWS
- Finding Projects
-- how to find upcoming or ongoing projects to join
-- how to source projects
- Project Execution
-- tips, tricks, methodologies
-- execution lead responsibilities
-- builder responsibilities
- Payments
-- making claims ahead of time
-- adjusting claims at the end
-- making the payment proposals
-- dealing with conflicts
- HOW DORG WORKS
-- Value Flows (roberto's diagram)
-- Rep & Tokens
-- org.json

**Comment by orishim** [comment]
For the last one "how dorg works" I think it could just be the existing "Governance" section and we add a page about Value Flows.

**Comment by benefacto** [comment]
Draft edits: https://app.gitbook.com/@dorg/s/-/~/drafts/-MGjWAzxVMQH_y2QtG5g/@activity
