### ISSUE TITLE
DAO wikipedia article as source of traffic

### ISSUE THREAD

**Issue by rihp** [dOrgTech/Handbook#21]
- https://en.wikipedia.org/wiki/DOrg

**Comment by orishim** [comment]
Might make more sense to add ourselves to https://en.wikipedia.org/wiki/Decentralized_autonomous_organization

**Comment by rihp** [comment]
Agreed, and quicker to do also.
Link to https://dorg.tech

**Comment by rihp** [comment]
Should be live now: 
https://en.wikipedia.org/wiki/Decentralized_autonomous_organization#List_of_DAOs

**Comment by rihp** [comment]
For future consideration: 
Some other projects also have their individual wiki pages. This IMO is an important sign of establishment.

See examples:
https://en.wikipedia.org/wiki/The_DAO_(organization)
https://en.wikipedia.org/wiki/Aragon_(project)
